### ISSUE TITLE
Remove Hex Editor from npp Plugin list

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/nppPluginList#126]
Due to a lot of unstable issues related to Hex Editor (one of them here) : 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3288#issuecomment-527181902

Could we consider to remove Hex Editor from the list?

**Comment by PeterCodar** [comment]
What alternative to this Hex Editor do you suggest?

**Comment by xylographe** [comment]
I never experienced problems with HEX-Editor plug-in (32-bit NPP).

**Comment by chcg** [comment]
@PeterCodar You may want to test https://github.com/chcg/NPP_HexEdit/releases/tag/0.9.5.19. Currently I didn't add it to the list because also with this version there seem to be still some major hang\crash issues still open.

**Comment by KrasnayaPloshchad** [comment]
@PeterCodar I like to use MadEdit-Mod, it‘s powerful for spell checking.
https://github.com/LiMinggang/madedit-mod
