### ISSUE TITLE
Test Plugin Locally - Dead Links on Documentation Page

### ISSUE THREAD

**Issue by viper3400** [notepad-plus-plus/nppPluginList#142]
Tried to test updated version of NppRexExtractorPlugin as described here: https://npp-user-manual.org/docs/plugins/#test-your-plugins-locally

But links to the tools located at https://notepad-plus-plus.org/pluginListTestTools are dead. Where I can download the tools?

![grafik](https://user-images.githubusercontent.com/11006334/67620171-296bd080-f804-11e9-9c5e-9d33b4d884a2.png)

**Comment by gurikbal** [comment]
[x86](https://web.archive.org/web/20190523164709/https://notepad-plus-plus.org/pluginListTestTools/notepad++.debug.x86.zip)

[x64](https://web.archive.org/web/20190523164709/https://notepad-plus-plus.org/pluginListTestTools/notepad++.debug.x64.zip)

**Comment by chcg** [comment]
@viper3400 Could you please recreate this issue at https://github.com/notepad-plus-plus/npp-usermanual/issues This is the repo where the webpage is maintained. Thanks.

**Comment by viper3400** [comment]
Created https://github.com/notepad-plus-plus/npp-usermanual/issues/46
