### ISSUE TITLE
发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢

### ISSUE THREAD

**Issue by logsin37** [notepad-plus-plus/nppPluginList#144]
发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢发表政见可以去你自己的Twitter上，不要来污染开源社区，谢谢

**Comment by CreativeQuilt** [comment]
This is spam
