### ISSUE TITLE
Additional plugins available

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/nppPluginList#155]
While improving the existing plugins list (see pull request https://github.com/notepad-plus-plus/nppPluginList/pull/154), I noticed that some of the plugins on the following site are missing:
http://www.scout-soft.com/index_npp_plugins.html

Specifically, the SQL, Print, and Linesort plugins are missing.

I recommend vetting them and adding them if appropriate.

**Comment by dail8859** [comment]
Does the author want them added?

**Comment by Gitoffthelawn** [comment]
I don't know, but half of their plugins are already in the NPP plugins list, and all their addons are listed in a single list on their website.

The Linesort plugin, in particular, offers some very unique and useful functionality.

**Comment by E3V3A** [comment]
Hex-Edit!!

**Comment by chcg** [comment]
@E3V3A Hexedit was added with https://github.com/notepad-plus-plus/nppPluginList/commit/379b2b8d2e7c1dc5177e3ea6274320e830e38093 and is available with N++ 7.9.1
