### ISSUE TITLE
Clickable links to the site of the author of the plugin.

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/nppPluginList#173]
Please make clickable links to the site of the author of the plugin.

![Безымянный](https://user-images.githubusercontent.com/3471892/74269519-488a6180-4d12-11ea-9c33-b4d34c3ecb52.png)

**Comment by chcg** [comment]
@andrecool-68 This needs to be implemented within N++. Seems https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp#L1079 need to be modified to support hyperlinks.

**Comment by donho** [comment]
I'll do it in the next release of Notepad++

**Comment by donho** [comment]
I have checked in the code, it's not that simple to do.
The edit field of win32 doesn't support clickable link. So sorry but this feature won't be implemented.
