### ISSUE TITLE
Add XMLTools

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/nppPluginList#18]
https://sourceforge.net/projects/npp-plugins/files/XML%20Tools/Xml%20Tools%202.4.9%20Unicode/

**Comment by CraigAlbright** [comment]
I second this request!

**Comment by chcg** [comment]
See https://github.com/morbac/xmltools/issues/12 about the blocking point with this plugin.

**Comment by chcg** [comment]
see https://github.com/notepad-plus-plus/nppPluginList/commit/636062080e596691fb8e85325097218b7f880c4e
