### ISSUE TITLE
add NppEditorConfig and setup its automated build

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/nppPluginList#19]
https://sourceforge.net/projects/editorconfig/files/EditorConfig-Notepad%2B%2B-Plugin/0.3.1/Unicode/NppEditorConfig.zip/download

https://github.com/editorconfig/editorconfig-notepad-plus-plus#readme

**Comment by chcg** [comment]
@KOLANICH What do you mean with automated build?

**Comment by KOLANICH** [comment]
>Appveyor build is available for this plugin

Thank you for noting, that is what I have meant.
