### ISSUE TITLE
This ANSI plugin is not compatible with your Unicode Notepad++.

### ISSUE THREAD

**Issue by BladeMight** [notepad-plus-plus/nppPluginList#21]
Actually after trying to install the plugin from releases page, it says:
![2018 11 15 - 17 53 16_rect](https://user-images.githubusercontent.com/11931888/48565245-c9d12980-e900-11e8-86d7-114c1eb9a08f.jpg)
Notepad++ version(downloaded debug version as mentioned [here](https://notepad-plus-plus.org/features/plugin-admin.html)):
![2018 11 15 - 17 53 32_rect](https://user-images.githubusercontent.com/11931888/48564664-81fdd280-e8ff-11e8-9ccf-6b7429295f44.jpg)
Was trying to get it to work with rebuilding using MinGW:
 - makefile (inside src folder):
```makefile
LIBS=-lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -lodbc32 -lodbccp32
DLLFLAGS=-municode -shared
DLLDEFINES=-D NDEBUG -D _WINDOWS -D _USRDLL -D NPPPLUGINLIST_EXPORTS -D _USING_V110_SDK71_ -D _WINDLL -D _UNICODE -D UNICODE
RCDEFINES=-D _UNICODE -D UNICODE -D _USING_V110_SDK71_ -D _UNICODE
CC=g++
RC=windres

all:
	$(CC) -c dllmain.cpp nppPluginList.cpp $(DLLDEFINES) $(DLLFLAGS)
	$(RC) -D _WIN64 $(RCDEFINES) nppPluginList.rc -o nppPluginList.ro
	$(CC) nppPluginList.o dllmain.o nppPluginList.ro $(LIBS) $(DLLFLAGS) -o nppPluginList.dll

x86:
	$(CC) -m32 -c dllmain.cpp nppPluginList.cpp $(DLLDEFINES) $(DLLFLAGS)
	$(RC) -F pe-i386 $(RCDEFINES) nppPluginList.rc -o nppPluginList.ro
	$(CC) -m32 nppPluginList.o dllmain.o nppPluginList.ro $(LIBS) $(DLLFLAGS) -o nppPluginList.dl
```

also not work, but it says that the plugin is not win32 app... Seems like MinGW doesn't built it correctly.

**Comment by dinkumoil** [comment]
Your report is somewhat unclear. I'll try to **guess** what is your problem.

As far as I can see you tried to install _nppPluginList.dll_ as a plugin in Notepad++ v7.5.9. Obviously you made two **wrong** assumptions:

1. _nppPluginList_ is **not** a plugin itself.
2. _nppPluginList_ is **not suitable** for a standard installation of Notepad++ v7.5.9 created by an installer or ZIP package from the official download sources.

_nppPluginList_ is a so called resource-only DLL, containing **no** executable code but a JSON file. Its intended purpose is to provide a list of available plugins, i.e. their names, version, author, download location and download checksum, to be used with the new build-in _Plugin Admin_ of Notepad++.

If I was wrong with my guessings please provide more clear informations about your problem. If I was right please close this issue.

**Comment by BladeMight** [comment]
@dinkumoil Okay I understand what are you talking about, then where should i put the `nppPluginList.dll`? And where does *Plugin Admin* menu appears in Notepad++?

> nppPluginList is not suitable for a standard installation of Notepad++ v7.5.9

Then which one *is* suitable? The build from appveyor or from source?

**Comment by BladeMight** [comment]
> new build-in Plugin Admin of Notepad++

I can't seem to find out how to start it in Notepad v7.6... The only things i found that: 
 - plugins menu shows nothing, 
 - about menu has plugins item which leads to http://docs.notepad-plus-plus.org/index.php/Plugin_Central 

so far..

**Comment by BladeMight** [comment]
>Portable installations of Notepad++ created with a ZIP package currently neither contain Plugin Admin nor the file nppPluginList.dll. Thus there will not show up an Plugin Admin entry in the Plugins menu.

Ah. That what it is... 
I'll close it up, is Plugin Admin will be available for portable build? Is that because wingup(and the libcurl) is not included inside zip packages? Why don't include it and make a portable version update'able too?

**Comment by dinkumoil** [comment]
> Why don't include it and make a portable version update'able too?

_WinGup_ is also used to update Notepad++ itself - it downloads an installer version. If you run a portable version this would be wrong. The author of Notepad++ is researching for a solution for that problem.

**Comment by BladeMight** [comment]
> it downloads an installer version. If you run a portable version this would be wrong. 

Yes, that is what i meant, if it knows where to find the installer version, it should be able to find the zip version as well(since they are on each release page), and download it instead of installer.

> The author of Notepad++ is researching for a solution for that 

Since he already found a solution for installer version there should similar for zip(portable) one.
