### ISSUE TITLE
Add AnalysePlugin

### ISSUE THREAD

**Issue by marunguy** [notepad-plus-plus/nppPluginList#22]
* [https://sourceforge.net/projects/analyseplugin/](https://sourceforge.net/projects/analyseplugin/)
* [https://sourceforge.net/projects/analyseplugin/files/binaries/](
https://sourceforge.net/projects/analyseplugin/files/binaries/)

**Comment by chcg** [comment]
Structure of the provided package is not matching with PA needs. See plugin manager commands:

>     Copy from: AnalysePlugin\AnalysePlugin.dll To: $PLUGINDIR$\ Validate Directory
>     Copy from: AnalysePlugin\*.txt To: $PLUGINDIR$\doc\AnalysePlugin Directory

AnalysePlugin.dll needs to be in the root dir of the zip file.

**Comment by chcg** [comment]
See #44
