### ISSUE TITLE
fstellari/nppplugins plugins fail to install

### ISSUE THREAD

**Issue by wesleywerner** [notepad-plus-plus/nppPluginList#236]
The site at https://sites.google.com/site/fstellari/nppplugins is no longer online. All plugins that point to this repository (7 by my count) error out when installed from the plugin admin interface.

It would be nice if these plugins are mirrored and rescued. I can't find them on github or sourceforge.

**Comment by ArkadiuszMichalski** [comment]
In the meantime you can download from archive:
https://web.archive.org/web/20200603050229/https://sites.google.com/site/fstellari/nppplugins

**Comment by chcg** [comment]
@Yaron10  @bruderstein do you have still a contact address of franco stellari ?

**Comment by Yaron10** [comment]
@chcg,

I have the following address: fstellari.public@gmail.com.
Please let me know when you've seen it so that I can remove it.

**Comment by chcg** [comment]
Created https://github.com/chcg/fstellari_rescue for the meantime until I get an answer from Franco Stellari how to proceed.

**Comment by Yaron10** [comment]
@chcg,

:+1:

**Comment by francostellari** [comment]
Google sites has changed.
The plugin description is still available at https://sites.google.com/site/fstellari/nppplugins
The plugins can be downloaded from GitHub at https://github.com/francostellari/NppPlugins
I will submit changes for the pl json

**Comment by francostellari** [comment]
I have tried to commit a new version of pl.x64.json with the new links but it fails for reasons that I don't understand.
![image](https://user-images.githubusercontent.com/50019234/95879904-e1abc500-0d44-11eb-8aa8-28e3691d631a.png)

**Comment by chcg** [comment]
@francostellari See https://ci.appveyor.com/project/donho/npppluginlist/builds/35727070/job/g5fcruorsg72od94/messages the SHA256 hash value is not correct.
