### ISSUE TITLE
Known broken plugins for PluginAdmin and reasons

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/nppPluginList#24]
- Packaging issue, see https://github.com/vladk1973/npp.connections/issues/5

		{
			"folder-name": "npp.connections",
			"display-name": "npp.Connections",
			"version": "1.0.1",
			"id": "c8dcdc4cf96594244f1a7da2884fd82caf0e6656108632c89fe3c6ab41dee16a",
			"repository": "https://github.com/vladk1973/npp.connections/releases/download/v1.0.1/npp.connections-1.0.1-x32.zip",
			"description": "This plugin allows Notepad++ to connect to MS SQL or Sybase servers. ODBC data sources, like a MySql Driver, are also supported",
			"author": "Vladimir Korobenkov",
			"homepage": "https://github.com/vladk1973/npp.connections"
		},

- Packaging issue multiple plugin in one zip, not supported by PluginAdmin

		{
			"folder-name": "NppPlugin_ChangeMarker",
			"display-name": "Change Markers",
			"version": "1.0",
			"id": "9df9fbc086c68a26950dafa624fa03e9a2a3ea500743a8afcde9d9c882b1448f",
			"repository": "http://www.brotherstone.co.uk/npp/changemarker/NppPlugin_ChangeMarker_Unicode_bin.zip",
			"description": "This plugin tracks changes made to documents, and enables navigation between changes, with a distinction being mafe between saved and unsaved changes. The change indicator is either a bar in the left margin or a specific highlighting. Or none.",
			"author": "Thell Fowler",
			"homepage": "http://codealignment.com"
		},

- Packaging issue config file not found in local subfolder /config, needed sqlite missing in zip

		{
			"folder-name": "nppColdFusion",
			"display-name": "ColdFusion Lexer",
			"version": "0.8.1",
			"id": "54317bc33af402d3b6f9285711bd018a622ed991d99301b0a5a7a2875d07d8ac",
			"repository": "https://downloads.sourceforge.net/project/npp-plugins/NppColdFusion/nppColdFusion-0.8.1.zip",
			"description": "Syntax highlighting, Call tips (Notepad++ 5.8.4 required) and autocomplete for the ColdFusion language",
			"author": "Ben Bluemel",
			"homepage": "https://bitbucket.org/bbluemel/nppcoldfusion/overview"
		},

- Packaging issue config file not found in local subfolder /config, N++ 7.6 doesn't start with this plugin

		{
			"folder-name": "ExternalLexerKVS",
			"display-name": "External Lexer KVS",
			"version": "1.0",
			"id": "7ba3132e9061aaa0972ff707d4973c785db2ea4b4da3838cf4817f120bcea8ea",
			"repository": "http://www.brotherstone.co.uk/npp/kvs/KVS_Unicode.zip",
			"description": "Syntax highlighting for the KVS language (KVIrc Scripting language). An example of an external lexer",
			"author": "Thell Fowler",
			"homepage": ""
		}

- WinGUP issue can't be unzipped

		{
			"folder-name": "EmmetNPP",
			"display-name": "Emmet",
			"version": "1.0.2",
			"id": "77d36f28beb5147ed2992ed26b184ca0354bb1bcf1e0f228b76934259085af2b",
			"repository": "http://download.emmet.io/npp/emmet-npp.zip",
			"description": "Emmet (ex-Zen Coding) is a web-developer's toolkit that can greatly improve your HTML &amp; CSS workflow",
			"author": "Sergey Chikuyonok",
			"homepage": "http://emmet.io"
		},

- Packaging issue config file not found in local subfolder /config, N++ 7.6 doesn't start with this plugin, uninstall not working

		{
			"folder-name": "AndroidLogger",
			"display-name": "AndroidLogger",
			"version": "1.2.7",
			"id": "817de52d78744a527a6ea00006c2644abd71c70aaa5563f07e26f2843061c94a",
			"repository": "https://sourceforge.net/projects/androidlogger/files/AndroidLoggerV1.2.7/AndroidLogger_Src.V1.2.7.zip",
			"description": "Lexer for logcat, with it you can highlight the log lines and the colors customizable. In additional, it can capture logs &amp; screenshot from device online.",
			"author": "Simbaba",
			"homepage": "https://sourceforge.net/p/androidlogger/"
		},

- WinGUP issue can't be unzipped

		{
			"folder-name": "NppBookmarkManager",
			"display-name": "Bookmark Manager",
			"version": "0.1.0.97",
			"id": "69e73ac848b0766d61b5d4082a119803d22acae094de1e573dc91e068e1d2863",
			"repository": "https://bitbucket.org/ViRuSTriNiTy/nppbookmarkmanager/downloads/NppBookmarkManager_0_1_0_97_Unicode.zip",
			"description": "This plugin adds simple bookmark functionality to Notepad++.\nBasically it provides shortcuts for defining / jumping to specific bookmarks as it is incorporated in many RAD tools.",
			"author": "ViRuSTriNiTy",
			"homepage": "https://bitbucket.org/ViRuSTriNiTy/nppbookmarkmanager"
		},

- Download not working by wingup

		{
			"folder-name": "Kstudio.MaxscriptExplorer",
			"display-name": "MaxScriptExplorer",
			"version": "1.5.2",
			"id": "757e384d23df4995230111fd4777d64e9a6e50f94ec25bc454a5c7a618b123a1",
			"repository": "https://3d-kstudio.com/download-manager.php?id=112",
			"description": "New plugin for navigation on maxscript project.\n\nFeatures:\n- Display the list of functions and structures from maxscript file(s).\n- Multiply project modes: Single file, Project folder, Opened files\n- Go to definition from working area or tree.\n- Ability to insert function with parameters into working area.\n- Navigation back/forward\n- Filter functions by text\n- Ability to hide private members of structs\n- Display tooltips with related comments and parameters for selected function.",
			"author": "Alexander Kramer",
			"homepage": "https://3d-kstudio.com/forum/trackscripts-news/maxscript-explorer-notepad-plugin-developers/"
		},

**Comment by dinkumoil** [comment]
I would like to add the following to this list:

* WinGUP issue, companion file gets unzipped with length of 0 bytes
* Plugin issue, companion files in local subfolder /NppSnippets not found

		{
			"folder-name": "NppSnippets",
			"display-name": "Snippets",
			"version": "1.4.0",
			"id": "26751a8805f273603d1f1d3d90459083750723310a66671a9a061f317eeaa1b4",
			"repository": "https://github.com/ffes/nppsnippets/releases/download/v1.4.0/NppSnippets-140-x32.zip",
			"description": "Adds the possibility to add code snippets to the current document by selecting it from a simple list.",
			"author": "Frank Fesevur",
			"homepage": "https://www.fesevur.com/nppsnippets"
		},

**Comment by chcg** [comment]
Regarding unzip issue, see https://github.com/notepad-plus-plus/wingup/issues/7

**Comment by chcg** [comment]
Download longer available:
	
	{
			"folder-name": "NppMenuSearch",
			"display-name": "NppMenuSearch",
			"version": "0.7.5",
			"id": "fba2177939eae03056b0baeb724fd73faabb95298cca4beea91fe0bc19c3df56",
			"repository": "http://www2.brotherstone.co.uk/npp/NppMenuSearch075.zip",
			"description": "Allows quick access to menu options by typing part of the command.",
			"author": "pitti_platsch",
			"homepage": "http://sourceforge.net/projects/nppmenusearch/"
		},

**Comment by chcg** [comment]
Unzip issue:

		{
			"folder-name": "NppPlates",
			"display-name": "NppPlates",
			"version": "0.1",
			"id": "55626266fcd322b2e4c0cc62b8cf4278ce53008b61b12bb4f99cfa21ab94d1da",
			"repository": "http://dl.dropbox.com/u/163495/NppPlates.zip",
			"description": "Generates HTML templates",
			"author": "Nir Elbaz",
			"homepage": "http://sourceforge.net/projects/notepad-plus/forums/forum/482781/topic/5333716"
		},

**Comment by chcg** [comment]
Message about incompatible plugin for:

		{
			"folder-name": "NamedBookmarks",
			"display-name": "Named bookmarks",
			"version": "1.2.0.0",
			"id": "b3963511a1d149aab5dc576159d664e26b9937ecb4c40197ed244f51b1452293",
			"repository": "http://www.dbaileyconsultancy.co.uk/npp_plugins/namedbookmarks.zip",
			"description": "The NamedBookmarks plugin lets the user add bookmarks to a file of C, C++, Java, C#, or HTML, by using a comment in the relevant language. It is then possible to display a drop down list of bookmarks in a file, and jump to one. Since bookmarks are just special comments, they are removed using normal editing procedures.",
			"author": "David Bailey",
			"homepage": ""
		},

**Comment by chcg** [comment]
No Https:

,
		{
			"folder-name": "NppSync",
			"display-name": "NppSync",
			"version": "1.0",
			"id": "bc9ccc7c47b445c4735b417718baeb14ae0b403f66b744c3c8578e829f2b7bd0",
			"repository": "http://snjezanat.net.amis.hr/storage/nppsync/NppSync_1.0.zip",
			"description": "Plugin that refreshes localhost pages in Chrome when their source has been modified in notepad++. It is a combination of two plugins: one for notepad++, other one for Chrome. Full details on installation and usage are in the included readme file.\nThis is a tiny plugin with not much more to expand on. It's written in DelphiXE2 so I doubt anyone will care to work on it further. If you want the source it's at https://github.com/evilworks/nppsync and if you have any requests write to email in the readme.",
			"author": "evilworks",
			"homepage": ""
		}

, see also fork: https://github.com/duzun/nppsync

**Comment by chcg** [comment]
Download not possible:

		{
			"folder-name": "PoorMansTSqlFormatterNppPlugin",
			"display-name": "Poor Man's T-Sql Formatter",
			"version": "1.6.10",
			"id": "9b013b43ffa3c4de550036c6299407d1f370f4ba90186c7b4987096577c8033a",
			"repository": "http://www.architectshack.com/GetFile.aspx?File=SqlFormatterNppPlugin.1.6.10.zip&amp;Page=PoorMansTSqlFormatter",
			"description": "A simple SQL formatter performing full multi-batch T-SQL formatting (individual statements, stored procedures, any DML, any DDL) with numerous formatting options.",
			"author": "Tao Klerks",
			"homepage": "http://www.architectshack.com/PoorMansTSqlFormatter.ashx"
		},

**Comment by chcg** [comment]
Unzip issue:

		{
			"folder-name": "NppExternalLexers",
			"display-name": "Powershell Lexer",
			"version": "1.0",
			"id": "9fcd14f72a14691487167a28991889c98ee29e6ba7a49cc1cb181db9de87720b",
			"repository": "http://poshcode.org/notepad++lexer/ExternalLexer.1.0.unicode.zip",
			"description": "Syntax highlighting and folding for Powershell scripts",
			"author": "Thell Fowler",
			"homepage": "http://poshcode.org/notepad++lexer/"
		},

**Comment by dinkumoil** [comment]
I did further investigations for unusable plugins. I found the following for the _Named bookmarks_ plugin:

@chcg wrote:

> Message about incompatible plugin for:
> 
> ````Z
> 	{
> 		"folder-name": "NamedBookmarks",
> 		"display-name": "Named bookmarks",
> 		"version": "1.2.0.0",
> 		"id": "b3963511a1d149aab5dc576159d664e26b9937ecb4c40197ed244f51b1452293",
> 		"repository": "http://www.dbaileyconsultancy.co.uk/npp_plugins/namedbookmarks.zip",
> 		"description": "The NamedBookmarks plugin lets the user add bookmarks to a file of C, C++, Java, C#, or HTML, by using a comment in the relevant language. It is then possible to display a drop down list of bookmarks in a file, and jump to one. Since bookmarks are just special comments, they are removed using normal editing procedures.",
> 		"author": "David Bailey",
> 		"homepage": ""
> 	},
>  ````

The error message tells not the truth about the real cause of failure. The plugin ZIP file contains the files `NamedBookmarks.dll` and `ClearWin32.dll`. The latter one has to be stored in the Notepad++ installation directory. i.e. at the **same directory level** like `notepad++.exe`.

**Comment by donho** [comment]
0 length issue is fixed.
Tested plugins : 
NppSnippets
NppSnippets
NppBookmarkManager
CodeAlignmentNpp
EmmetNPP

**Comment by dinkumoil** [comment]
@donho 
Thank you! I can confirm that.

@chcg 
Additionally I have tested the _NppSync_ plugin. You wrote

> No Https for repo link

would cause the plugin installation to fail. Seems not to be true. This plugin can be unzipped now as well.

@donho 
Currently we are mostly faced with misleading error messages by _GUP.exe_ respectively during the plugin installation/updating process in common. Especially when a plugin developer performs his tests for plugin deployment this is bad. It will cause also a support nightmare when users report these error messages in the support forum. Would you please have a look at that?

**Comment by chcg** [comment]
@dinkumoil 
Regarding NppSync http download is working, just want to use https for security reasons. 
On using https://snjezanat.net.amis.hr/storage/nppsync/NppSync_1.0.zip there is an outdated certificate issue:

> snjezanat.net.amis.hr verwendet ein ungültiges Sicherheitszertifikat. Das Zertifikat gilt nur für folgende Namen: *.amis.hr, amis.hr Das Zertifikat ist am Donnerstag, 8. November 2018, 00:59:59 abgelaufen. Die aktuelle Zeit ist 20. Dezember 2018, 19:04. Fehlercode: SSL_ERROR_BAD_CERT_DOMAIN

At that time I didn't made up my mind completely how to handle legacy plugins just supporting http links and thought the problem seen in validation script was due to just accepting https links, but that is not the case.

**Comment by Aidolii** [comment]
The use of the Translate plugin causes the program to crash using the default translation engine, and it doesn't seem the way it hooks into Bing Translate works anymore.

**Comment by chcg** [comment]
@Aidolii This is not the right place to report such an issue. Should go to https://sourceforge.net/projects/npptranslate/files/bin/, also there was no active development the last years. The bing translator api changed to https://azure.microsoft.com/de-de/services/cognitive-services/translator-text-api/ some time ago.

**Comment by Aidolii** [comment]
I'm saying it should be removed from the list.

**Comment by chcg** [comment]
@Aidolii I don't think so as the the default is still usable, see https://sourceforge.net/p/npptranslate/wiki/Version%20Guide/:

- Default engine is MyMemory(https://mymemory.translated.net/) (for new installation)

**Comment by favorini** [comment]
JSLint has the wrong homepage (it has the one for the following plugin, JSON Viewer)
`"homepage": "https://github.com/kapilratnani/JSON-Viewer"`

**Comment by chcg** [comment]
@favorini Thanks for the hint. Corrected with https://github.com/notepad-plus-plus/nppPluginList/commit/71b9eb2bc271d605e771637219e8ca309ab4de03

**Comment by chcg** [comment]
@dinkumoil Would you like to create a version of nppRegEx with dll version info inside, see https://github.com/larryb82/npp-regexhelper/issues/2 ?

**Comment by dinkumoil** [comment]
@chcg 

I'm already working on it when I have some time. But due to the repository is missing the used plugin framework I have to make huge adaptions to the framework I use. Furthermore the used Delphi version is different from that one I use, which causes additional work. In short it is a work-in-progress, but at the moment I have no time to work on this project.

My motivation is also low since the plugin uses the Delphi-build-in RegEx engine which is derived from PCRE and changes with every Delphi version, thus the plugin's RegEx processing is different from that of Notepad++ which uses the _boost lib_ regex flavour. So the syntax is not the same and also the results can be different.

**Comment by chcg** [comment]
@dinkumoil Thought it is maybe just a recompilation with the resource infos add. Thanks anyway for taking a look into it.

**Comment by donho** [comment]
@dinkumoil
> Currently we are mostly faced with misleading error messages by GUP.exe respectively during the plugin installation/updating process in common.

This issue has been fixed, hasn't it?

**Comment by dinkumoil** [comment]
@donho 

Some month ago you asked me to create an [issue in the Notepad++ issue tracker](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5928) concerning error handling of _Plugins Admin_. There I provided a detailed checklist for testing it.

Since I'm currently out of time to work on this topic by myself, I recommend you take that list as a basis for testing error handling by yourself.
