### ISSUE TITLE
Redesign the stuff

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/nppPluginList#31]
I think it is an extremily bad idea to hardcode plugins list into a dll; dll is an executable code, to minimize the profits of injecting malicious code there the lib should be updated as rarely, as makes sense. So I think it's better to keep the info in a signed (with a good enough signature scheme, no obsolete stuff like md5, which is still advertised by notepad-plus-plus.org) JSON downloaded from a repo, and allow users to use any count of repos.

**Comment by KOLANICH** [comment]
But why to use of the dll at all? Why not just sign data files?

**Comment by chcg** [comment]
@donho What do you think about the suggestions of dinkumoil above?

**Comment by donho** [comment]
@dinkumoil @chcg  

> It would also be possible to include the JSON file as a resource into the DLL. Then it could be loaded with LoadLibraryEx with parameter dwFlags set to LOAD_LIBRARY_AS_DATAFILE | LOAD_LIBRARY_AS_IMAGE_RESOURCE and the JSON could be retrieved with calls to FindResource and LoadResource.

Nice idea.
I'll modify it this evening.

**Comment by donho** [comment]
@KOLANICH 
> But why to use of the dll at all? Why not just sign data files?

There's no standard way so far to sign JSON. And since there's code signing certificate for Notepad++,  the choice is obvious.

**Comment by KOLANICH** [comment]
>There's no standard way so far to sign JSON.

You can sign a file using openssl and your x.509 cert. gpg can also be used for that.

**Comment by favorini** [comment]
How about using [JSON Web Signature (JWS)](https://en.wikipedia.org/wiki/JSON_Web_Signature)? Also see [Signing a json document or string with x509 certificate](https://stackoverflow.com/questions/40447670/signing-a-json-document-or-string-with-x509-certificate).

**Comment by donho** [comment]
@KOLANICH @favorini  with a code signing certificate ?

**Comment by donho** [comment]
@dinkumoil @chcg Sorry for the delay, but it's been done at least;
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fbffdd8825ecafb7f351a2db6f094cfe4e821288

**Comment by favorini** [comment]
@donho Not sure what certs work, but I guess JWS has some issues. [PASETO](https://paseto.io/) is a newer alternative. There is a [.NET implementation](https://github.com/idaviddesmet/paseto-dotnet). Seems like pulling the JSON data off the web somewhere would be better than a static file included with the executable.

**Comment by KOLANICH** [comment]
> with a code signing certificate ?

Yes, with it.

**Comment by p0358** [comment]
Even pulling updated DLL for plugin list update regularly would be much better than just hardcoding it forever and without auto-updates with particular Notepad++ version

**Comment by p0358** [comment]
@donho I understand you're talking about costs. Code signing certificate requires to be signed by a Certificate Authority in order to be trusted by Windows (Windows has its trusted CA store). With custom private/public key signature verification, this is not needed. You only need to include your public key in executable, which could be used to verify downloaded list with a signature created using secret private key.
Bundled public key's integrity would be protected by executable being signed with code signing cert (that's omitting that if somone can patch executable locally, they can just as well do other things right away instead of playing around with patching Notepad++).
