### ISSUE TITLE
Something missing for ARM build in resource.h ?

### ISSUE THREAD

**Issue by MarkusBodensee** [notepad-plus-plus/nppPluginList#310]
@chcg @donho 

Sorry for the inconvenience and if this is not a real problem. I am not able to test the ARM build, since I have no such device.

I just browsed through the code and found these lines (file: resource.h, line: 31 and below). I was wondering if something for ARM build must be added there?

https://github.com/notepad-plus-plus/nppPluginList/blob/a9b71e3473a09103f09bb815ddc7cbafa8f3b320/src/resource.h#L31

**Comment by donho** [comment]
The symbol `_WIN64` includes ARM64 already.

**Comment by MarkusBodensee** [comment]
@donho 
Thank you for your reply.

What I meant with "below" is, that this in turn results in not having a define like:
`#define PLJSON "pl.arm64.json"` present which is used in `nppPluginList.rc` file.

But looks like this does not have any negative effect in this case. But just wanted to mention to be on safe side. Thank you.

**Comment by chcg** [comment]
@donho The finding from @MarkusBodensee is valid. For the arm64 dll the json for x64 is currently used, if you do no magic on your local machine. This could be seen in the build folder within the nppPluginList.res file.

**Comment by MarkusBodensee** [comment]
Sorry @donho, I should have added the details of my second post directly to the initial one. Thanks @chcg for taking another look into it.

I am happy that my review could help fixing the ARM build. I think in this case, a new release of `nppPluginList` should be build and bundeled into `Notepad++ V8.0` to get the full ARM experience.

---
Below the line I want to share a link to stackoverflow, which I found yesterday evening during some researches to understand the `.rc` script. Maybe it is interesting for others which come along, or otherwise at least for me to keep it in mind. The "magic define numbers" are responsible to embed the `.json` files to the `.dll` libs. So @chcg is indeed right that previously the x64 list was embedded into ARM.

https://stackoverflow.com/questions/2933295/embed-text-file-in-a-resource-in-a-native-windows-application
