### ISSUE TITLE
NppCalc for Notepad++ 64bit ?

### ISSUE THREAD

**Issue by balaji-ch** [notepad-plus-plus/nppPluginList#314]
Can somebody provide NppCalc for 64 bit ? It is available only for 32bit NPP. Are there any alternates ?

**Comment by chcg** [comment]
See https://sourceforge.net/projects/nppcalc/. Unfortunately there is no contact data there as far as I see. The source code seems to be in delphi. There exists a free edition https://www.embarcadero.com/products/delphi/starter?aldSet=en-GB. But probably that needs someone with delphi expertise to recompile and adapt the source for 64bit. Maybe https://community.notepad-plus-plus.org/category/5/plugin-development or https://community.notepad-plus-plus.org/category/4/help-wanted is the right place to raise this request.
