### ISSUE TITLE
hi i don't know how to pull a request. but i have a plugin 

### ISSUE THREAD

**Issue by gurikbal** [notepad-plus-plus/nppPluginList#32]
[https://github.com/gurikbal/Text-Grabber/commit/373373ea165b97c9fd9edba85dc6fd31d142f8e6](url)
please add this "Text Grabber" plugin

**Comment by chcg** [comment]
Data for the list from your repo:
	
{
			"folder-name": "Text Grabber",
			"display-name": "Text Grabber Plugin",
			"version": "1.0.5",
			"id": "1e68181b237ce81e9bb0a8ac7a328139d0b467f65aba117c7e53d5b8ea1ff6c9",
			"repository": "https://github.com/gurikbal/Text-Grabber/releases/download/1.5/text_grabber_v1.0.5.zip",
			"description": "This plugin can grab text from images such as .jpg .png .bmp .tif and also support .pdf files",
			"author": "Gurikbal Singh",
			"homepage": "https://github.com/gurikbal/Text-Grabber"
},

**Comment by chcg** [comment]
See https://help.github.com/articles/creating-a-pull-request-from-a-fork/ how to create a pull request
- fork
- create a branch
- commit change
- create pull request

**Comment by dinkumoil** [comment]
@gurikbal 

Googeling for _NSOCR.dll_ retrieves a link to this web site:

https://www.nicomsoft.com/files/ocr/help/files.htm

This site states:

> Redistribution of Nicomsoft OCR files
> Note:
>            You may not copy or redistribute files without obtaining the appropriate license

You should follow this rule or you could run into serious trouble.

@chcg I'm not sure if the plugin should be distributed via Plugin Admin **without** ensuring that there is a valid redistribution license. The plugin ZIP file doesn't contain such a license.

**Comment by chcg** [comment]
@dinkumoil But at https://www.nicomsoft.com/products/ocr/order/ seems to be changed to freeware.

**Comment by dinkumoil** [comment]
@chcg Yes, I saw that. But I'm not sure that this automatically means that everybody can redistribute the DLL file of this product **without a license**.

It may be that the requirement of a redistribution license pointed under the link I've provided is obsolete, but only an advocate can answer this. It would be more secure to contact that company to obtain such a license or at least the confirmation that the DLL can be redistributed without a license now.

**Comment by gurikbal** [comment]
https://www.nicomsoft.com/products/ocr/order/
the page said sdk is totally free with licence key and "**Please note we don't support Nicomsoft OCR SDK anymore, don't ask us for technical support, updates, sources, etc.**"
so i can't connect there admin of nicomsot.com
can i make trialware plugin? 
user who can download sdk and below licence key

**Comment by gurikbal** [comment]
https://www.nicomsoft.com/products/ocr/license/
free software terms not added
because sdk and licence key is free now
there
