### ISSUE TITLE
Add a column for plugin release date

### ISSUE THREAD

**Issue by kenijo** [notepad-plus-plus/nppPluginList#33]
The idea is to be able to sort by release date to know which are the newer plugins that are released.

**Comment by gurikbal** [comment]
as 3p plugin i mean some plugins are updatable after install

**Comment by cmeriaux** [comment]
@chcg can you confirm this enhancement is accepted by you and @donho ? I motivated to help you guys be adding in the json plugin list the release date of existing plugin. I just need your confirmation to avoid useless action because it's quiet a job

**Comment by kenijo** [comment]
I'm definitely in favor of this.

**Comment by chcg** [comment]
For me it would be ok to add this piece of information. For plugin manager I try to add it to the latestUpdate tag, see e.g. https://github.com/bruderstein/npp-plugins-x64/commit/4eda138499de64aad33b19bb41d19da4712576af. Additionally this would also require an extension of the N++ dialog. @cmeriaux would you also take over this SW part?

**Comment by cmeriaux** [comment]
@chcg thanks for the feedback.
I will do the task.
I'll also do the update of software. For my understanding, it's quite easy to add a column. Adding a sort capability looks like more difficult.

**Comment by chcg** [comment]
The part here is already finished to become visible to the user PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5780 needs to be integrated.
