### ISSUE TITLE
zip or 7z install    PluginAdmin(nppPluginList)    for notepad++ 7.6.0  .7.6.1  this ansi plugin is not compatible

### ISSUE THREAD

**Issue by deeplyloving** [notepad-plus-plus/nppPluginList#35]
zip or 7z install    PluginAdmin(nppPluginList)    for notepad++ 7.6.0  .7.6.1  this ansi plugin is not compatible

**Comment by chcg** [comment]
@deeplyloving ? Which ANSI plugin?  ANSI is unsupported from N++ for a long time already.

**Comment by dinkumoil** [comment]
@deeplyloving 
The _nppPluginList.dll_ is not a plugin itself. This file contains the list of available plugins as a JSON file.

@chcg @donho 
This is another example for a misleading error message ragarding _GUP.exe_, _Plugin Admin_ and the whole plugin installation process. The error handling should be reviewed and fixed ASAP.

**Comment by chcg** [comment]
@dinkumoil 
Thanks for explaining what the issue really is about. I didn't get it from the description.
Already saw such messages also with companion dlls in the search path for plugins.
 
In this case it is a N++ issue of the plugin system and a misunderstanding where to store the nppPluginList.dll

**Comment by deeplyloving** [comment]
@chcg  @dinkumoil     7z or zip  install version     is not support PluginAdmin?

**Comment by chcg** [comment]
@deeplyloving Starting with https://notepad-plus-plus.org/download/v7.6.2.html
- Add Plugins Admin module into portable version (zipped package).
PA is also available for the portable versions.
