### ISSUE TITLE
Plugins list display- cannot easily read the last column on right of table

### ISSUE THREAD

**Issue by Daksol** [notepad-plus-plus/nppPluginList#388]
The Description column in the Plugins list display is almost invisible, since no room for it on the page.

If you scroll to bottom of table you can then use a left-right scroll bar, but then that hides one of the columns on the left.

Is it possible to make this more readable? - Possibly reduce the left and right padding - there is a lot of white space.

Lots of people have put in a lot of work to create plugins -  a shame to hide the detailed info about them. 

See screenshot
![NPPlugins64](https://user-images.githubusercontent.com/42010857/145583026-2c47ca70-f3e8-4a33-89bc-48a7f7fe91fc.PNG)

**Comment by chcg** [comment]
@Daksol The rendering of the markdown is done by github. On my screen there is no problem. Which resolution and browser do you use? At least you could use the zoom function of the browser

![grafik](https://user-images.githubusercontent.com/12630740/145687237-f87b2857-e03a-496c-baa9-0d0719a248ce.png)
