### ISSUE TITLE
Notepad++ LSP Client Plugin

### ISSUE THREAD

**Issue by pidgeon777** [notepad-plus-plus/nppPluginList#395]
A developer has created this awesome Notepad++ plugin:

https://github.com/Ekopalypse/NppLspClient

It implements a cool and essential feature missing in Notepad++: [LSP](https://microsoft.github.io/language-server-protocol/).

It would be great to add it to the list of currently available plugins.

**Comment by chcg** [comment]
@Ekopalypse Do you think your plugin is already stable enough to be published?

**Comment by Ekopalypse** [comment]
Stable? Probably, but I don't want it to be officially available yet, as there are too many things that don't work as they should, and above all I'm in the process of reorganising the structure of the plugin, as it has become a bit confusing and which potentially means that existing functions could suddenly cause problems again. 
I hope that by the end of January next year I will be able to announce the first beta version, which should then be stable, all the basic functions will work as they should and give users a pleasant experience.
Thank you.
