### ISSUE TITLE
NppGitSCM updated version

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/nppPluginList#399]
Plugin Admin still has 1.4.4.2 but the latest is [1.4.5.1](https://github.com/vinsworldcom/nppGitSCM/releases/tag/1.4.5.1)

**Comment by chcg** [comment]
@vinsworldcom You could create a PR to update plugins infos integrated into the PA of next N++ version. For this version I added it myself.

**Comment by chcg** [comment]
Appveyor compilation issue is due to a temporary download issue of a other plugin.
