### ISSUE TITLE
Problem generating ctags in a project with many subdirs.

### ISSUE THREAD

**Issue by nuxil** [notepad-plus-plus/nppPluginList#401]
I am real sorry. 
I posted this at the wrong place. it was suppost to be an issue for the NppTags plugin. 

This plugin is greate, if it only worked correctly.

Assume i have set my workspace to <X:\Dev\MyProject> and have a setup like this 
<X:\Dev\MyProject>
<X:\Dev\MyProject\MainSrc>
<X:\Dev\MyProject\Module1Src>
<X:\Dev\MyProject\Module2Src>
<X:\Dev\MyProject\Module3Src>
and so on.

It will only create a ctags.sqlite file for the first directory you pressed generated in.
As in. if you had main.cpp open from <X:\Dev\MyProject\MainSrc> , this is the place it will put the ctags.sqlite file.
And if you try to generate ctags for <X:\Dev\MyProject\Module1Src>. it just makes the same ctags.sqlite file
and puts it in <X:\Dev\MyProject\MainSrc>.

Idealy the ctags.sqlite file should be in <X:\Dev\MyProject> if the Workspace is set to this directory

**Comment by chcg** [comment]
Closed as the right place as already found is https://github.com/ffes/npptags/issues/6
