### ISSUE TITLE
ElasticTabstops not in Plugins Admin

### ISSUE THREAD

**Issue by Abulos** [notepad-plus-plus/nppPluginList#433]
Hi

I use ElasticTabstops to view tab delimited files in Notepad++. ElasticTabstops does a good job of aligning the data in the correct columns.

Seems to be broken lately - throwing errors where I already had it installed.

When I updated Notepad++ to the latest version ElasticTabstops  does not appear in Plugins Admin

However it is in the plugin list (https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md)

Is ElasticTabstops still supported in Notepad++? If not supported is there an alternative for viewing tab delimited files in Notepad++?

If not supported and no alternative what version of Notepad++ should I roll back to so I can keep using ElasticTabstops?

**Comment by dail8859** [comment]
@Abulos There's no alternative to the plugin that I know of. I haven't had the time or interest much lately to make the required changes and recompile the plugin and get it updated in the plugin list.

**Comment by chcg** [comment]
@Abulos Please create an issue at the relevant elastictabstop issue list mentioned above.
