### ISSUE TITLE
missing plugins in plugins admin

### ISSUE THREAD

**Issue by atesin** [notepad-plus-plus/nppPluginList#446]
hi... i want a plugin for ctrl+click a function to takes me to definition .... i found some plugins for this [in the official x64 list](https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md) (searched for **ctags**) , but only ONE plugin "NppTags" is shown on my plugins admin .. i want to install another but doesnt appear

**Comment by chcg** [comment]
I guess you want to try TagLEET. See:
https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x64.json#L1216-L1224
That plugin is not compatible with newer N++ version. So it depends on your N++ version if you see it within plugin admin list or not.

The overall list of plugins is not reflecting the compatibility issues. The issues just happen for the x64 version so far.

**Comment by atesin** [comment]
hi, i know it is closed, but btw
... do you know some configuration or plugin for jump to function/object definition with ctrl+click or similar shortcut, while editing source code of popular languages?? .. or to rename all references to a function/object in all related files at once?

i hadn't found any info in documentation

**Comment by chcg** [comment]
@atesin To my knowledge N++ doesn't have this functionality. What is available is the function list panel to jump to a function/method. Rename without any knowledge of the internal structure of the language/files could be done to some degree via find in files.
Maybe with some programming specific plugins these IDE like features are available.
