### ISSUE TITLE
Problems in carrying out the steps described in the manual

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/nppPluginList#454]
1. Created a debug version with gcc
2. Saved the current nppPluginList.json under ...\plugins\Config
3. Edited as described in [manual ](https://npp-user-manual.org/docs/plugins/#do-your-pr-to-join-plugin-list)(hopefully)
4. Started Npp and PluginAdmin but I don't see the plugin listed

What did I forget to do?

![image](https://user-images.githubusercontent.com/47723516/168791394-728819de-fec2-4ee1-a812-bf9c6e4e15f3.png)

**Comment by Ekopalypse** [comment]
It looks like the issue is that a debug build of gcc does not count as a debug version :-(

![image](https://user-images.githubusercontent.com/47723516/168825894-fc45a259-9b22-4c33-b20f-d20d34c4d0a4.png)

**Comment by rdipardo** [comment]
> It looks like the issue is that a debug build of gcc does not count as a debug version :-(

Did you define `_DEBUG` for the GCC compiler, the way the VC++ project file does for MSVC?

https://github.com/notepad-plus-plus/nppPluginList/blob/567f7b8c4acdd64346650fe9928dcdf81357c76c/vcxproj/nppPluginList.vcxproj#L160

Other relevant info:

- what compiler, linker flags are you using?

- 32- or 64-bit? I believe MinGW will decorate functions with the `@n` suffix in 32-bit mode [unless you pass `--kill-at` to the linker][0]



[0]: https://github.com/ScintillaOrg/lexilla/issues/10#issuecomment-846486337

**Comment by Ekopalypse** [comment]
Thank you for your interest in my problem.
It looks like gcc wants to see an environment variable called DEBUG with some value, so I defined DEBUG=1 and it creates a debug build. The file is > 100MB and I can use gdb to see the symbols.
For the build process I followed the instructions on how to build with gcc.
I opened a git-bash, exported DEBUG=1 and ran mingw32-make.
Don't be confused by the name, it still sees that I'm on x64 and builds a 64bit executable.

But you are right that DEBUG is not passed to the build. In the makefile would be a
[CPP_DEFINE += DEBUG](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c9b177bb9e0eddf4bb858746fe9e4e667a458c02/PowerEditor/gcc/makefile#L63)
but this is commented and if I comment it out then the build fails.
Probably the reason why it is commented.

**Comment by rdipardo** [comment]
Sorry to ask another silly question, but did you also try editing the `pl.x64.json` manifest under `src` and recompiling nppPluginList.dll? Ordinarily the list is embedded as a resource string:

https://github.com/notepad-plus-plus/nppPluginList/blob/567f7b8c4acdd64346650fe9928dcdf81357c76c/src/resource.h#L33-L37

To be honest, I wasn't aware you could edit an external manifest and have it dynamically loaded by the module 😊

**Comment by Ekopalypse** [comment]
Don't be sorry - I'm grateful for any help I get.
No, I didn't, I followed the [instruction from the manual](https://npp-user-manual.org/docs/plugins/#test-your-plugins-locally) ... hmm ... maybe that's one way to make it work.
I'll give it a try. Thank you very much. :-)

**Comment by rdipardo** [comment]
I think the issue is more than just the failing feature test in [`PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp`][0]. I'm also having trouble bypassing the signature check in [`PowerEditor/src/MISC/Common/verifySignedfile.cpp`][0]. Dropping a signed plugin module into `plugins\Config` doesn't work for me. I even tried removing the verification code altogether, to no effect.

It's of no use without a signature, but you can try building the plugin manager with MinGW after hard-coding the edited list:

    cd src
    windres nppPluginList.rc -o resources.o
    g++ -D_DEBUG -D_WINDOWS -D_USRDLL -DNPPPLUGINLIST_EXPORTS -g3 -O0 -fPIC --shared dllmain.cpp resources.o -o nppPluginList.dll

Using gcc (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0
I should point out that this distribution targets the legacy msvcrt runtime, not the post-2015 ucrt one

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c9b177bb9e0eddf4bb858746fe9e4e667a458c02/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp#L311
[1]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c9b177bb9e0eddf4bb858746fe9e4e667a458c02/PowerEditor/src/MISC/Common/verifySignedfile.cpp#L54

**Comment by rdipardo** [comment]
I should have suggested this to start with, but if you check what the pre-processor emits in debug mode, you'll see the expected code path is actually getting compiled:

    g++ -DDEBUG --std=c++17 -Wpedantic -Wall -g -DSCI_OWNREGEX \
    -I../../scintilla/include -I../../lexilla/include -I../src \
    -I../src/ScintillaComponent -I../src/TinyXml -I../src/TinyXml/tinyXmlA \
    -I../src/MISC/Common -I../src//MISC/PluginsManager -I../src/MISC/Process \
    -I../src/WinControls/AboutDlg -I../src/WinControls -I../src/WinControls/AnsiCharPanel \
    -I../src/WinControls/ContextMenu -I../src/WinControls/ColourPicker \
    -I../src/WinControls/TabBar -I../src/WinControls//ImageListSet \
    -I../src/WinControls/StaticDialog -I../src/WinControls/shortcut \
    -I../src/WinControls/ToolBar -I../src/json -I../../boostregex \
    -E ../src/WinControls/PluginsAdmin/pluginsAdmin.cpp > pluginsAdmin.pre.processed.cpp

![pluginsAdmin cpp debug path](https://user-images.githubusercontent.com/59004801/168933988-9b698980-c8e2-44f7-9150-35eeaa73397c.png)

That leaves the question of why GDB appeared to be stepping into the release code path in your [screen capture][0]. 🤔

[0]: https://github.com/notepad-plus-plus/nppPluginList/issues/454#issuecomment-1128894042

**Comment by Ekopalypse** [comment]
Btw ... I'm using `g++.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0`
I think, that is the one you use as well, correct?

**Comment by chcg** [comment]
Maybe you want to check:
https://github.com/chcg/notepad-plus-plus/blob/master/PowerEditor/gcc/makefile#L63
unclear why it is commented out.

**Comment by Ekopalypse** [comment]
Thanks - I tried that already, with the result that the compilation fails. I assume that is why it is commented.

**Comment by chcg** [comment]
Sorry I didn't spot it above.

**Comment by rdipardo** [comment]
@Ekopalypse,
>  I tried that already, with the result that the compilation fails.

In fact, it fails at exactly the code path you want: the call to `PluginsAdminDlg::initFromJson()`:

    ../src/WinControls/PluginsAdmin/pluginsAdmin.cpp: In member function 'bool PluginsAdminDlg::initFromJson()':
    ../src/WinControls/PluginsAdmin/pluginsAdmin.cpp:709:55: error: no matching function for call to 'std::basic_ifstream<char>::basic_ifstream(generic_string&)'
      709 |         ifstream nppPluginListJson(_pluginListFullPath);
        |                                                       ^
    In file included from ../src/WinControls/PluginsAdmin/pluginsAdmin.cpp:20:
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:584:9: note: candidate: 'template<class _Path, class _Require> std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const _Path&, std::ios_base::openmode) [with _Path = _Path; _Require = _Require; _CharT = char; _Traits = std::char_traits<char>]'
      584 |         basic_ifstream(const _Path& __s,
        |         ^~~~~~~~~~~~~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:584:9: note:   template argument deduction/substitution failed:
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:583:32: error: 'class std::__cxx11::basic_string<wchar_t>' has no member named 'make_preferred'
      583 |       template<typename _Path, typename _Require = _If_fs_path<_Path>>
        |                                ^~~~~~~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:592:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(std::basic_ifstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]'
      592 |       basic_ifstream(basic_ifstream&& __rhs)
        |       ^~~~~~~~~~~~~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:592:39: note:   no known conversion for argument 1 from 'generic_string' {aka 'std::__cxx11::basic_string<wchar_t>'} to 'std::basic_ifstream<char>&&'
      592 |       basic_ifstream(basic_ifstream&& __rhs)
        |                      ~~~~~~~~~~~~~~~~~^~~~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:567:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::ios_base::openmode]'
      567 |       basic_ifstream(const std::string& __s,
        |       ^~~~~~~~~~~~~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:567:41: note:   no known conversion for argument 1 from 'generic_string' {aka 'std::__cxx11::basic_string<wchar_t>'} to 'const string&' {aka 'const std::__cxx11::basic_string<char>&'}
      567 |       basic_ifstream(const std::string& __s,
        |                      ~~~~~~~~~~~~~~~~~~~^~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:549:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const wchar_t*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::ios_base::openmode]'
      549 |       basic_ifstream(const wchar_t* __s,
        |       ^~~~~~~~~~~~~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:549:37: note:   no known conversion for argument 1 from 'generic_string' {aka 'std::__cxx11::basic_string<wchar_t>'} to 'const wchar_t*'
      549 |       basic_ifstream(const wchar_t* __s,
        |                      ~~~~~~~~~~~~~~~^~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:534:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::ios_base::openmode]'
      534 |       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
        |       ^~~~~~~~~~~~~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:534:34: note:   no known conversion for argument 1 from 'generic_string' {aka 'std::__cxx11::basic_string<wchar_t>'} to 'const char*'
      534 |       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
        |                      ~~~~~~~~~~~~^~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:523:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]'
      523 |       basic_ifstream() : __istream_type(), _M_filebuf()
        |       ^~~~~~~~~~~~~~
    c:\winlibs-mingw-msvcrt\current\include\c++\11.2.0\fstream:523:7: note:   candidate expects 0 arguments, 1 provided
    mingw32-make[1]: *** [makefile:239: bin.x86_64-debug.build/WinControls/PluginsAdmin/pluginsAdmin.o] Error 1
    mingw32-make[1]: *** Waiting for unfinished jobs....


Looks like an issue with MinGW's support of the C++17 standard.
I suspect more polyfill is needed than what [gcc-fixes.h] already provides.
As it currently makes debug builds impossible, there will definitely be a patch against N++ when this gets figured out.

[gcc-fixes.h]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/gcc/gcc-fixes.h

**Comment by rdipardo** [comment]
@Ekopalypse, does it work better like this?

~~~diff
diff --git a/PowerEditor/gcc/makefile b/PowerEditor/gcc/makefile
index 4f0ce59f..c97ced4d 100644
--- a/PowerEditor/gcc/makefile
+++ b/PowerEditor/gcc/makefile
@@ -60,7 +60,7 @@ else
 BUILD_TYPE := debug
 BUILD_SUFFIX := -debug
 CXXFLAGS += -Og -g -Wall -Wpedantic -Wconversion-null
-#CPP_DEFINE += DEBUG
+CPP_DEFINE += DEBUG
 endif
 
 #
diff --git a/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp b/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp
index 8a091ad1..34f52373 100644
--- a/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp
+++ b/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp
@@ -706,7 +706,11 @@ bool PluginsAdminDlg::initFromJson()
 #ifdef DEBUG // if not debug, then it's release
 	
 	// load from nppPluginList.json instead of nppPluginList.dll
+#ifdef __MINGW32__
+	ifstream nppPluginListJson(_pluginListFullPath.c_str());
+#else
 	ifstream nppPluginListJson(_pluginListFullPath);
+#endif	
 	nppPluginListJson >> j;
 
 #else //RELEASE

~~~

[0001-Fix-GCC-Debug-build.diff.txt](https://github.com/notepad-plus-plus/nppPluginList/files/8721455/0001-Fix-GCC-Debug-build.diff.txt)

**Comment by Ekopalypse** [comment]
Brilliant, YES, this works!!
Thank you very much.

![image](https://user-images.githubusercontent.com/47723516/169230402-b823c312-5b41-47de-9998-b1a6ed41cf8c.png)

Don't be confused by the "build time", it still shows yesterday's date because I replaced the existing exe with the newly created exe.
