### ISSUE TITLE
Order plugins alphabetically

### ISSUE THREAD

**Issue by cpmcgrath** [notepad-plus-plus/nppPluginList#46]
When you open the plugin admin there's no order to the plugins, this could be resolved programmatically or introducing a convention that the json file should be ordered by the Display name field.

**Comment by chcg** [comment]
Currently the order is just the time of adding a plugin to the list which is not very intuitive and useful for the user. So the correction could be either done in the json input or the PluginAdmin component itself with the option to sort also for other criteria like the already requested last update.

**Comment by chcg** [comment]
See also https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fd32585c14836b46a1b40c79bce706cd96767526
