### ISSUE TITLE
SelectToClipboard Plugin Update

### ISSUE THREAD

**Issue by benpratt** [notepad-plus-plus/nppPluginList#471]
The author updated the SelectToClipboard plugin in GitHub but the changes weren't submitted to the nppPluginList to allow users to get the new plugin.

Attached are three diff files for the changes. It doesn't appear as though SelectToClipboard was previously available on arm64 but a build is available so that's an add but the x64 and x86 versions are just an update of the to the new version.

[pl.arm64.json.txt](https://github.com/notepad-plus-plus/nppPluginList/files/8893987/pl.arm64.json.txt)
[pl.x64.json.txt](https://github.com/notepad-plus-plus/nppPluginList/files/8893988/pl.x64.json.txt)
[pl.x86.json.txt](https://github.com/notepad-plus-plus/nppPluginList/files/8893989/pl.x86.json.txt)

**Comment by chcg** [comment]
Added via https://github.com/notepad-plus-plus/nppPluginList/commit/18ff3b0ffdc0ba570ed7ad23c0fdde58fc4e51c7
