### ISSUE TITLE
TextFX in plugin list

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/nppPluginList#472]
Per recent notes in the Forum, including [this post in the 8.4.1 announcement thread](https://community.notepad-plus-plus.org/post/77106) and [this access violation with textfx](https://community.notepad-plus-plus.org/topic/23158/access-violation-specifically-with-unwrap-text-within-textfx), it looks like the TextFX plugin, which was abandoned 13 years ago by its author, is finally not fully compatible with even the 32bit Notepad++ as of v8.4.

Should it just be removed from the x86 plugin list?  Or should we add the `"npp-compatible-versions": "[,8.3.3]",` to its x86 entry (which, if I have understood correctly, will make it so that Notepad++ will actively disable that plugin if it finds it)?

**Comment by donho** [comment]
@pryrt 
> Or should we add the `"npp-compatible-versions": "[,8.3.3]",` to its x86 entry (which, if I have understood correctly, will make it so that Notepad++ will actively disable that plugin if it finds it)?

Sounds good in this way!
