### ISSUE TITLE
DocMonitor plugin

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/nppPluginList#479]
@donho,

Per [this discussion](https://community.notepad-plus-plus.org/topic/23285/is-docmonitor-v2-2-the-same-as-built-in-monitoring), it came to light that the Plugins Admin is still listing your ancient [DocMonitor v2.2](https://sourceforge.net/projects/npp-plugins/files/DocMonitor/) plugin from 2008.  Given that it's 32-bit only, and Notepad++ has natively supported Monitoring mode since [v6.9.2 in 2016](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Change-Log-v4-v6#692), is there a good reason that the plugin is still advertised?  Or should we just remove it from the list, since it is so out-of-date and has been replaced by the builtin feature?

**Comment by donho** [comment]
@pryrt 
You're absolutely right.
This plugin is obsolete and it should be removed from the list.
I'll remove it ASAP.
Thank you for your heads up!
