### ISSUE TITLE
Dark Theme Mode pulled from GitHub?

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/nppPluginList#497]
1903cff failed with a 404 trying to locate the [Dark Theme Mode] plugin:

https://ci.appveyor.com/project/donho/npppluginlist/builds/44859531/job/5v77dku8o374nnq0/messages

Transient network timeouts happen all the time, but I think this one merits closer attention.

The download link is unreachable, and it even looks like the @MyTDT-Mysoft account was deleted.

~~~sh-session
$ curl -sI https://github.com/MyTDT-Mysoft | head -2
HTTP/2 404 
server: GitHub.com
    
$ nslookup https://github.com/MyTDT-Mysoft 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find https://github.com/MyTDT-Mysoft: NXDOMAIN
~~~

A snapshot of the repository was [archived within the past year][0], in case anyone still needs the plugin.

The Plugin List can be revised to target the archived link (for however long it remains valid), or simply drop the plugin from future releases.

[Dark Theme Mode]: https://github.com/MyTDT-Mysoft/DarkTheme-Npp-Plugin
[0]: https://web.archive.org/web/20220724123913/https://github.com/MyTDT-Mysoft/DarkTheme-Npp-Plugin

**Comment by chcg** [comment]
I have also forked it at https://github.com/chcg/DarkTheme-Npp-Plugin.

**Comment by rdipardo** [comment]
@chcg,
I think bc5cd19 can be reverted now.

[The host] was down only temporarily, for the unfortunate reason [explained by @MyTDT-Mysoft](https://github.com/notepad-plus-plus/nppPluginList/issues/497#issuecomment-1256135375) above.

The plugin still functions in current N++ versions; binary compatibility with 64-bit pointers is no problem, since the only release is for x86.

![DTM-1 0-x86](https://user-images.githubusercontent.com/59004801/211176395-5e243ee1-b981-466e-94ac-3cb8f9dfbf4f.png)

[The host]: https://github.com/MyTDT-Mysoft/DarkTheme-Npp-Plugin
