### ISSUE TITLE
When does the new plugin list get distributed?

### ISSUE THREAD

**Issue by cpmcgrath** [notepad-plus-plus/nppPluginList#55]
Hi, I've just installed 7.6.3 and noted that the list is now sorted alphabetically but Code Alignment is still not appearing on the list. Does the refresh only happen when one of the first two bits of the version number changes?

**Comment by TaoK** [comment]
Same question for Poor Man's T-Sql Formatter.

**Comment by chcg** [comment]
The idea is that the newest tag here is part of the next release, but @donho seems to have missed V1.0.5. As the dll needs to be signed by donho just he could create the dll.

**Comment by donho** [comment]
The old certificate is expired, and I'm working on getting a new one.
I will make the progress asap.

**Comment by donho** [comment]
@chcg I am planning to do a new Notepad++ release this weekend.
Could you make a new release of Plugin List ?

**Comment by chcg** [comment]
@donho As you already did I think this is obsolete. Right?
