### ISSUE TITLE
Missing plugin

### ISSUE THREAD

**Issue by RichardD2** [notepad-plus-plus/nppPluginList#560]
[ComparePlus](https://github.com/pnedev/comparePlus) is listed in v1.5.7 of both the [32-bit](https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x86.md) and [64-bit](https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md) plugin list.

However, Notepad++ does not display it in the Plugins Admin list, even though it's using list version 1.5.7:

![image](https://user-images.githubusercontent.com/2158265/211526696-2c3a3f2b-82a0-4edf-955d-e63f7ad7a55c.png)

I have tried on multiple different computers, both with and without the plugin already installed, with the same result.

Notepad++ v8.4.8

**Comment by chcg** [comment]
@RichardD2 Have you also checked the installed and incompatible tab? I can't reproduce the issue with 

![grafik](https://user-images.githubusercontent.com/12630740/211546070-8cf2b722-c2af-4b42-a293-f6eb2cb369eb.png)

Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\...\npp.8.4.8.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2364
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by RichardD2** [comment]
Odd - it wasn't showing as installed, and the toolbar wasn't visible, but it *was* showing in the "updates" tab.

I've installed the update, and now it's back.

Thanks for your help.
