### ISSUE TITLE
TextFX plugin update

### ISSUE THREAD

**Issue by pchris7489** [notepad-plus-plus/nppPluginList#584]
Hello,

It seems that in Notepad++, it still considers that the TextFX plugin is obsolete/not updated anymore,
But the devellopement for the latest versions for TextFX for NPP is active since 2022, see : 

https://sourceforge.net/p/npp-plugins/bugs/354/

The new location for the latest TextFX (working on latest versions of NPP is here : 

https://github.com/rainman74/NPPTextFX2/releases

Thank you for corrections for this issue in latest NPP Plugin Admin window

![image](https://user-images.githubusercontent.com/16174847/222908488-8bf6113e-28d6-4679-8624-7c73b6915b96.png)

**Comment by chcg** [comment]
Fixed by https://github.com/notepad-plus-plus/nppPluginList/pull/592
