### ISSUE TITLE
doc/plugin_list Markdown table syntax compatibility - empty line missing before tables

### ISSUE THREAD

**Issue by git-user314** [notepad-plus-plus/nppPluginList#603]
Markdown tables in `doc/plugin_list_*.md` files are not detected as tables with some Markdown implementations, because there is no empty line between the table and the previous paragraph.

If `validator.py` were to be edited to place empty lines where approriate, the Markdown syntax of these files would be more compatible with different Markdown implementations.

This issue can be seen for example by using "*Pandoc*" or "*Pandoc GitHub-flavored Markdown*" preview options with *ghostwriter* Markdown editor, whereas "*cmark-gfm*" option does work correctly.

Related links:

- Implementation of the plugin list `.md` generation:
    - issue #158
    - PR #177
- Markdown tables (but these don't mention requiring empty lines(?)):
    - Pandoc Markdown tables: <https://pandoc.org/MANUAL.html#tables>
    - GFM tables: <https://github.github.com/gfm/#tables-extension->

**Comment by chcg** [comment]
Updated md files from PR with https://github.com/notepad-plus-plus/nppPluginList/commit/0d85c48de0918267bd82d20e6c2c8f1a11e12c2d
