### ISSUE TITLE
Can't open Notepad++ ver. 8.5.1

### ISSUE THREAD

**Issue by NonMuss** [notepad-plus-plus/nppPluginList#607]
![Notepad++ Screenshot 2023-04-01 175803](https://user-images.githubusercontent.com/126918157/229323324-468a7102-9f88-4a78-a752-03fb87ccd407.png)

pressing yes or no yeilds nothing

**Comment by chcg** [comment]
There is already an update available, see PR #600 . This could just be fixed with the next N++ update. To fix it in the meantime you could download the latest version from https://github.com/molsonkiko/JsonToolsNppPlugin/releases and extract the zip file to your N++ plugin dir.

**Comment by NonMuss** [comment]
Thanks for letting me know.
