### ISSUE TITLE
Ndjson support ?

### ISSUE THREAD

**Issue by kelibox** [notepad-plus-plus/nppPluginList#659]
I need the Ndjson viewer. 
JsonTools and JsonViewer do not support that.
Thanks a lot.

**Comment by chcg** [comment]
@kelibox Is there a existing N++ plugin supporting Ndjson format? If not this is not the right place for a feature request. Maybe the existing plugins could be extended and you could place a feature request for the plugins.

**Comment by kelibox** [comment]
ok
