### ISSUE TITLE
Compare Plugin redirects to the ComparePlus Plugin

### ISSUE THREAD

**Issue by matt-linn-ves** [notepad-plus-plus/nppPluginList#668]
https://github.com/pnedev/compare-plugin v 2.0.2 listed in the plugins list, and appears in the plugins list in the Notepad++ application points to https://github.com/pnedev/comparePlus v1.1.0

Might it make sense to remove the Compare plugin and just have the compareplus plugin only?

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/nppPluginList/pull/491. The repo got renamed and therefore both now link to https://github.com/pnedev/comparePlus. The older version is still available at https://github.com/pnedev/comparePlus/tree/Compare_v2 .
