### ISSUE TITLE
Adding GZ viewer?

### ISSUE THREAD

**Issue by ctr** [notepad-plus-plus/nppPluginList#703]
Could https://github.com/Pascal-Krenckel/NppGZipFileViewer be added to the plugin list please?

I have no affiliation to this plugin. I'm just a user who found this on google while trying to read a .gz file in notepad++.

Many thanks

**Comment by chcg** [comment]
@ctr As written in https://github.com/Pascal-Krenckel/NppGZipFileViewer/issues/6 a zip package is needed to be able to add it.

**Comment by ctr** [comment]
Is this something I can do, or must the original author do it? If I can do it, could you possibly point me to instructions on how to make the needed zip package?

**Comment by chcg** [comment]
@ctr That needs to be done by the plugin author as access to e.g. https://github.com/Pascal-Krenckel/NppGZipFileViewer/releases/tag/v2.2.0 assets is needed.
