### ISSUE TITLE
notepad++ 新版能否实现.....

### ISSUE THREAD

**Issue by hqhbaby** [notepad-plus-plus/nppPluginList#706]
notepad++ 标签栏 能否实现功能 
1.鼠标指向标签时才显示关闭按钮 
2 鼠标指向标签栏时自动激活当前标签页 
3.右键关闭当前标签页

**Comment by chcg** [comment]
https://translate.google.com/?sl=auto&tl=en&text=notepad%2B%2B%20%E6%A0%87%E7%AD%BE%E6%A0%8F%20%E8%83%BD%E5%90%A6%E5%AE%9E%E7%8E%B0%E5%8A%9F%E8%83%BD%0A1.%E9%BC%A0%E6%A0%87%E6%8C%87%E5%90%91%E6%A0%87%E7%AD%BE%E6%97%B6%E6%89%8D%E6%98%BE%E7%A4%BA%E5%85%B3%E9%97%AD%E6%8C%89%E9%92%AE%0A2%20%E9%BC%A0%E6%A0%87%E6%8C%87%E5%90%91%E6%A0%87%E7%AD%BE%E6%A0%8F%E6%97%B6%E8%87%AA%E5%8A%A8%E6%BF%80%E6%B4%BB%E5%BD%93%E5%89%8D%E6%A0%87%E7%AD%BE%E9%A1%B5%0A3.%E5%8F%B3%E9%94%AE%E5%85%B3%E9%97%AD%E5%BD%93%E5%89%8D%E6%A0%87%E7%AD%BE%E9%A1%B5%0A&op=translate


Can the notepad++ tab bar function be realized?
1. The close button is only displayed when the mouse points to the label
2 Automatically activate the current tab page when the mouse points to the tab bar
3. Right-click to close the current tab

@hqhbaby Feature requests for N++ as far as I understand. So the correct issue queue is https://github.com/notepad-plus-plus/notepad-plus-plus/issues
