### ISSUE TITLE
CSVLint Plug-in crashing

### ISSUE THREAD

**Issue by DebbieKat** [notepad-plus-plus/nppPluginList#748]
I'm experiencing issues recently with the CSVLint plug-in crashing upon opening files (not necessarily files created using CSVLint either, just unrelated files being opened in Notepad++). When I open the file, it seems it's no longer supporting long file names either and reverting them to the old 8 character name/3 character extension limit.
<img width="77" alt="Screenshot 2024-03-18 095653" src="https://github.com/notepad-plus-plus/nppPluginList/assets/24721316/97df13ea-d359-4eee-a29b-83fddb71bf04">
<img width="200" alt="Screenshot 2024-03-18 095642" src="https://github.com/notepad-plus-plus/nppPluginList/assets/24721316/73c37a65-6b5f-4154-b17c-2db447d05da6">

**Comment by DebbieKat** [comment]
Also, when I try to copy my original text from the file causing CSVLint to crash into a new file and attempt to save it, it's also defaulting to the 8.3 naming convention. It won't let me rename it to the complete name I had.

**Comment by chcg** [comment]
Please report this at https://github.com/BdR76/CSVLint/issues. Add info on used CVSLint, N++ and Windows version.
