### ISSUE TITLE
Task List URL not up to date?

### ISSUE THREAD

**Issue by sdasda7777** [notepad-plus-plus/nppPluginList#755]
Hi, I'm not exactly sure what the main page of the Task List plugin is, but the Google Code page seems to be deserted, while the plugin still gets updates irregularly. I think the current source is this repo, but I'm not sure: https://github.com/Megabyteceer/npp-task-list

**Comment by chcg** [comment]
As google code hosting service stopped  https://code.google.com/archive/p/npp-task-list/ is just for reference still available and not actively usable anymore. I updated to the forked github homepage.
