### ISSUE TITLE
Permanently in overtype mode, regardless of what the editor says

### ISSUE THREAD

**Issue by Bonesall** [notepad-plus-plus/nppPluginList#756]
![issue](https://github.com/notepad-plus-plus/nppPluginList/assets/18477063/b1f87245-8fbc-43e8-a5ba-75381dc7d54c)
Unsure if this is the intended use of the program, but it is impossible to insert text on the ascii side of the editor.
I tried switching modes inside the editor itself with no luck. No other program is in overtype mode, just Npp hex editor. I tried switching modes in other programs and coming back to Npp and it's in the same mode. Seems to be stuck on overtype regardless of windows settings. Running Win 10, current update as of 12/04/2024, Npp v8.4.8, HEX-editor v0.9.12

**Comment by chcg** [comment]
@Bonesall This is not the right place to report this. As this is a hex editor issue it should be reported at https://github.com/chcg/NPP_HexEdit/issues
