### ISSUE TITLE
How to pre-install plugins

### ISSUE THREAD

**Issue by duaneellissd** [notepad-plus-plus/nppPluginList#775]
Hello - we are in the process of setting up a large deployment of numerous windows machines.

And as part of this I want the IT group to pre-install Notepad++ - (they know how to do this)
But also a along list of notepad++ plugins listed here

https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md

My question is this: I do not want every user of these machines to have to install the plugins. Instead, I want the machines to come with these things *PRE-INSTALLED" - but I do not see a way to do that.

Is there some scheme that would simplify this with Notepad++ - ie: Pre-install plugins for all users?

**Comment by donho** [comment]
There are pre-install plugins from Notepad++ installer side. However, there's no support for the customized plugin list.
All I can see is that you download the plugins you want, and deploy them to users' machines.
