### ISSUE TITLE
WinGup fails to download Preview HTML (still)

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/nppPluginList#791]
#785 fixed the test runner by decoding the download URLs for *Preview HTML*. But WinGup is still requesting the encoded ones, and the host is still rejecting 'em:

<div align="center">
<img width="480" alt="preview-html-dl-borked" src="https://github.com/user-attachments/assets/62ad34e8-68f2-48c7-882f-66957798aed9">
</div>

Looks like we need to decode the URLs right in the JSON manifest. My bad for not just doing that sooner 😖

**Comment by rdipardo** [comment]
> Looks like we need to decode the URLs right in the JSON manifest.

Not so fast. WinGup doesn't know enough to strip the query string from the URL; if it's passed in when it's already decoded, WinGup will try to save the zipball to an invalid path:

<div align="center">
<img width="480" alt="gup-sux" src="https://github.com/user-attachments/assets/75fd0978-26d1-4861-b5c6-85888803db90">
</div><br>


The end result is that WinGup silently fails to install the plugin (hence the extra debug message shown above).

This is a more general problem with parametrized URLs. WinGup constructs the download path pretty much blindly from the web resource name, and the standard [`::PathFindFileName` function](https://github.com/notepad-plus-plus/wingup/blob/97187c6f35dcce65b5e26a1adc002fb566cde71f/src/winmain.cpp#L1276) doesn't perform any kind of validation.

There's no point changing the plugin list until WinGup can sanitize URLs of invalid file path characters. That would definitely improve WinGUP, but then again the only plugin affected right now is *Preview HTML*, which was [abandoned](https://fossil.2of4.net/npp_preview/wiki/Deprecation) some time ago.

I could more easily publish an updated plugin version from [my fork](https://github.com/rdipardo/npp_preview), avoiding the mess of parametrized URLs altogether.

Leaving this open until I decide.

**Comment by chcg** [comment]
@rdipardo I think it is not worth the effort to adapt WinGUP for just one outdated plugin.

**Comment by rdipardo** [comment]
Agreed.

What WinGup really needs is better error reporting, like handling a 404 response as what it really is, and not a [checksum mismatch](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14490#issuecomment-1857106203). But that's another issue.

I'll make a release from my fork sometime soon.
