### ISSUE TITLE
Remove ScrollPastEOF plugin?

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/nppPluginList#82]
Is this plugin needed any more?

https://github.com/notepad-plus-plus/nppPluginList/blob/fbe073016d85ca1d45cb7a255a2e852957eac48c/src/pl.x86.json#L887-L894

Since the plugin admin is for N++ 7.6+ it is guaranteed to have the "Enable scroll beyond last line" setting.

**Comment by chcg** [comment]
I didn't check if the functionality of a plugin is part of N++ already and therefore obsolete.
