### ISSUE TITLE
Preview HTML plugin fails to install, without error message

### ISSUE THREAD

**Issue by vor0nwe** [notepad-plus-plus/nppPluginList#83]
The plugin was added as per pull request [#67](https://github.com/notepad-plus-plus/nppPluginList/pull/67). As far as I can see, it should work fine.

In a clean install of Notepad++ 7.6.6 (64-bits), the Plugins Admin shows the plugin normally. If I try to install it, however, Notepad++ restarts but the plugin is not installed, no menu entry is created, no plugin directory is created, nothing is done as far as I can see. No message is shown, either.

Is there some log where I can read what the updater has (not) done, and for what reason?

If not, what can I do to figure out what's going wrong, and why the plugin wasn't installed?

**Comment by MetaChuh** [comment]
@vor0nwe 
if i use telerik fiddler to monitor the web traffic, at an installation attempt no traffic is initialised to
`https://fossil.2of4.net/npp_preview/zip/PreviewHTML32.zip?name=&uuid=v1.3.2.0-32` or `https://fossil.2of4.net/npp_preview/zip/PreviewHTML64.zip?name=&uuid=v1.3.2.0-64`

i have no idea why though, but i would suggest to try with an url not requiring post parameters, like: `https://fossil.2of4.net/npp_preview/zip/PreviewHTML64.zip` as this is the only difference to other urls i can see on the quick.

**Comment by MetaChuh** [comment]
@vor0nwe 

as i can see, your site is generating the zips of your packages on demand, and the `name=` parameter defines the sub-folder name within your generated zips, omitting to generate a sub-folder, if `name=` is left empty.

**available solutions:**
1) you have to url encode your get parameters, to get them working, **test them**, and make a new pr.
2) you have to provide static content packages that don't require get parameters, **test them**, and make a new pr.

here is a working PreviewHTML x86 example with url encoded get params:
```
		{
			"folder-name": "PreviewHTML",
			"display-name": "Preview HTML",
			"version": "1.3.2.0",
			"id": "b7538d5b4c61e7232ad6befe3a5eb1799544a4de741d4acd896716e9273f260b",
			"repository": "https://fossil.2of4.net/npp_preview/zip/PreviewHTML32.zip%3Fname%3D%26uuid%3Dv1.3.2.0-32",
			"description": "Preview HTML files inside Notepad++ (or in a floating window) without having to save them first.",
			"author": "Martijn Coppoolse",
			"homepage": "https://fossil.2of4.net/npp_preview"
		},
```

-----

**important note: please debug test your next pr before you submit it.**

**guide how to test a custom nppPluginList on 7.6.6 x86:**

* download <kbd>[npp.7.6.6.bin.zip](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.bin.zip)</kbd> and extract it to your desktop.

* download <kbd>[pl.x86.json](https://github.com/notepad-plus-plus/nppPluginList/raw/master/src/pl.x86.json)</kbd>
copy it to `npp.7.6.6.bin\plugins\Config` and rename it to `nppPluginList.json`.

* rename `npp.7.6.6.bin\plugins\Config\nppPluginList.dll` to `nppPluginList.dl_` to make sure you don't use it by accident.

* download <kbd>[Notepad++.Win32.Unicode Debug.exe](https://ci.appveyor.com/api/buildjobs/6334xpxkpr0m5qy0/artifacts/Notepad%2B%2B.Win32.Unicode%20Debug.exe)</kbd>
and copy it to `npp.7.6.6.bin\`

* launch `npp.7.6.6.bin\Notepad++.Win32.Unicode+Debug.exe` to edit and test your personal `nppPluginList.json` file.

(repeat the same for x64, using the x64 files)

many thanks for your great plugin and best regards.
