### ISSUE TITLE
New release 1.0.9 ?

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/nppPluginList#87]
@chcg Notepad++ v7.7 RC will be out soon.
What do you think to do a new release of nppPluginList 1.0.9 ?

**Comment by chcg** [comment]
@donho I added PR #88 and #89, resorted the list and updated the version infos.
-> Moved the tag after this. List seems to be fine for 7.7 RC

**Comment by donho** [comment]
Thank you @chcg
